/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* src = "nand1.v:1.1-3.10" *)
module nand1(a, b, c);
  (* src = "nand1.v:1.20-1.21" *)
  input a;
  wire a;
  (* src = "nand1.v:1.28-1.29" *)
  input b;
  wire b;
  (* src = "nand1.v:1.37-1.38" *)
  output c;
  wire c;
  assign c = ~(b & a);
endmodule
